repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: trailing-whitespace
        args: ['--markdown-linebreak-ext=md']
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: detect-private-key
      - id: detect-aws-credentials
        args: ['--allow-missing-credentials']
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.70.1
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
      - id: terraform_tflint
default_stages: [commit, push]
