name: e2e-all-examples-parallel

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  getExampleDirectories:
    name: Get example directories
    runs-on: ubuntu-latest
    outputs:
      directories: ${{ steps.dirs.outputs.directories }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get Terraform directories for evaluation
        id: dirs
        # examples/ci-cd/gitlab-ci-cd -> excluded since GitLab auth, backend, etc. required
        # examples/eks-cluster-with-external-dns -> excluded until Rout53 is setup
        # examples/observability/eks-cluster-with-amp-amg-opensearch -> TODO - needs to be updated to run example
        run: |
          EXCLUDE_EXAMPLES='examples/eks-cluster-with-external-dns,examples/ci-cd/gitlab-ci-cd,examples/observability/eks-cluster-with-amp-amg-opensearch'
          DIRS=$(python3 .github/workflows/examples_tfplan.py)
          echo "::set-output name=directories::$DIRS"

  deploy:
    name: E2E Example
    needs: getExampleDirectories
    runs-on: ubuntu-latest

    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read
    strategy:
      fail-fast: false
      matrix:
        tf_working_dir: ${{ fromJson(needs.getExampleDirectories.outputs.directories) }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials from Test account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.ROLE_TO_ASSUME }}
          aws-region: us-west-2
          role-duration-seconds: 3600
          role-session-name: GithubActions-Session

      - name: Terraform Job
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Terraform Fmt
        id: fmt
        run: terraform fmt -check -recursive -list -no-color

      - name: Terraform Init
        id: init
        run: terraform init -reconfigure
        working-directory: ${{ matrix.tf_working_dir }}

      - name: Terraform Validate
        id: validate
        working-directory: ${{ matrix.tf_working_dir }}
        run: terraform validate -no-color

      - name: Terraform Plan
        id: plan
        working-directory: ${{ matrix.tf_working_dir }}
        run: terraform plan -no-color
